server:
  port: 9020

spring:
  application:
    name: simple-base-generator-service


simple:
  generator:
    project:
      # 初始化压缩包地址
      initProjectZipUrl: /temp/initProject.zip
      # 解压覆盖生成项目压缩包操作的临时目录
      newProjectAndZipTempPath: /temp/simple/new