server:
  port: 13020

spring:
  application:
    name: demo-base-generator

simple:
  base:
    #simple-base-generator
    generator:
      project:
        #开启代码压缩包生成，缺省默认关闭
        enabled: true
        # 初始化压缩包地址
        initProjectZipUrl: /temp/initProject.zip
        # 解压覆盖生成项目压缩包操作的临时目录
        newProjectAndZipTempPath: /temp/simple/new
