// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package cn.iosd.demo.grpc.proto.person;

public final class AddressBookProto {
  private AddressBookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonHelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonHelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonHelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonHelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014person.proto\"\"\n\022PersonHelloRequest\022\014\n\004" +
      "name\030\001 \001(\t\"#\n\020PersonHelloReply\022\017\n\007messag" +
      "e\030\001 \001(\t2I\n\013PersonHello\022:\n\016PersonSayHello" +
      "\022\023.PersonHelloRequest\032\021.PersonHelloReply" +
      "\"\000B4\n\036cn.iosd.demo.grpc.proto.personB\020Ad" +
      "dressBookProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PersonHelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonHelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonHelloRequest_descriptor,
        new String[] { "Name", });
    internal_static_PersonHelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PersonHelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonHelloReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
