// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package cn.iosd.demo.grpc.proto.person;

public interface PersonHelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonHelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
