// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package cn.iosd.demo.grpc.proto.person;

public interface PersonHelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonHelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
