server:
  port: 11040
spring:
  application:
    name: simple-demo-socketio-one
simple:
  ## 无Redis配置情况下，默认开启Socket单机
  redisson:
    enabled: true
    type: standalone
    config:
      ## 单体模式
      standalone:
        address: redis://127.0.0.1:6379
        password:
        database: 0
  socketio:
    #缺省项为false
    enabled: true
    port: 12010
    upgradeTimeout: 1000000
    pingTimeout: 6000000
    pingInterval: 25000