version: '3'
services:
  redis:
    image: redis:7.0.11
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/conf:/usr/local/etc/redis"
      - "./redis/data:/data"
    command:
      redis-server --notify-keyspace-events Ex --requirepass redisp123456 --appendonly yes
